import type { SqlParameter } from "../SqlParameter.js";

/**
 * Generates SQL parameter names for query builders.
 */
export class QueryParameter {
    private readonly parameters: SqlParameter[] = [];

    /**
     * Adds a parameter and returns its generated SQL placeholder.
     *
     * @param value Parameter value.
     * @param type Optional provider-specific parameter type.
     */
    public add(
        value: unknown,
        type?: unknown
    ): string {
        const name = `p${this.parameters.length}`;

        this.parameters.push({
            name,
            value,
            type
        });

        return `@${name}`;
    }

    /**
     * Returns the parameters generated by this instance.
     */
    public getParameters(): SqlParameter[] {
        return [...this.parameters];
    }
}