import type { SqlParameter } from "../SqlParameter.js";

/**
 * Represents a provider-neutral SQL command.
 *
 * The SQL text is generated by the query layer while parameter
 * values remain separate from the SQL statement.
 */
export interface SqlCommand {
    readonly sql: string;
    readonly parameters: SqlParameter[];
}